#
ec_board_ctrl :
  eth_iface: rteth0
  sync_cycle_time_ns: 1000000
  #sync_cycle_time_ns: 2000000
  #sync_cycle_time_ns: 0
  sync_cycle_offset_ns: 300000000
  sync_point_ns : 500000
  power_off_boards: false
  reset_micro : true
  
ec_boards_base :
  app_mode : run_mode
  #app_mode : config_mode
  robot_name : NoNe
  read_SDOs : false
  use_pipes : true
  log_level : 1
  #fault_power_off : true
  use_ecat_pos_as_id : false

zmq_pub :
  base_port : 9000
  uri : "tcp://*:"
  fd_timeout_us : 100000

zmq_rep :
  uri: "tcp://*:5555"
  zmq_rcvtimeo_ms : 500
  #pipe_prefix : "/tmp/nrt_pipes/"

ati_config :
  ati_ip_addr : 192.168.1.1
  ft_ecat_pos : 1
  save_calib_matrix : false
  #calib_mat_file : ../examples/ati_ft6_calib/data/ones.txt
  calib_mat_file : ../examples/ati_ft6_calib/data/Calib_matrix_Cogimon_right_Foot_ft_147_sens8.txt
  dump_log : true


#############################
## GENERIC config
#############################

LpESC_X:
  sign: 1
  pos_offset: 0
  control_mode : 3B_motor_pos_ctrl
  pid :
    position: [100000.0 , 0.0 , 1.0]

LpHandESC_X:
  sign: 1
  pos_offset: 0
  control_mode : 3B_motor_pos_ctrl
  pid :
    position: [100000.0 , 0.0 , 1.0]

HeriHandESC_X:
  sign: 1
  pos_offset: 0
  control_mode : 3B_motor_pos_ctrl
  pid :
    position: [100000.0 , 0.0 , 1.0]
    
CentAcESC_X: &CentAcESC_X
  sign: 1
  pos_offset: 0
  enable_sandbox: false
  enable_pos_filter: false  
  control_mode : idle
  pid :
    position: [220.0 , 0.0 , 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    #impedance:  [0.0, 0.0, 5.0, 0.001, 0.08]
    impedance:   [250.0, 5.0, 2.0, 0.001, 0.08]
  aux_pdo : # names defined in SDO index 0x8002 
     _rd :  [ pos_ref_fb ]
     _rd :  [ pos_ref_fb, motor_enc_warn, motor_enc_err, link_enc_warn, link_enc_err ]
     _rd :  [ iq_out_fb ]
     _wr :  [ iq_ref ]
     _wrd : [ "iq_offset&&iq_out_fb" ]
     _wrd : [ "ts&&rtt" ]

Ft6Msp432ESC_X:
  analog_sample_freq_HZ: 20000

AinMsp432ESC_X:
  analog_sample_freq_HZ: 1000

TJuntionESC_X:
  aux_pdo :
    rd : []

PowF28M36ESCESC_X:
  aux_pdo :
    rd : [ FSM ]

TestESC_X:
  aux_pdo : # names defined in SDO index 0x8002 
     rd :  [ pos_ref_fb ]
     _rd :  [ pos_ref_fb, motor_enc_warn, motor_enc_err, link_enc_warn, link_enc_err ]
     _rd :  [ iq_ref_fb, id_ref_fb ]
     _wr :  [ iq_ref ]
     _wrd : [ "iq_offset&&iq_out_fb" ]
     wrd : [ "ts&&rtt" ]



